export {
  hungerUrgency,
  thirstUrgency,
  fatigueUrgency,
  resourceQuality,
  distanceFactor,
  distanceFactorSquared,
  explorationUncertainty,
  reproductionUrgency,
  partnerDesirability,
  lonelinessUrgency,
  socialDrive,
  relationshipAffinity,
  helpNeedFactor,
  threatFactor,
  vulnerabilityFactor,
  confrontationAdvantage,
} from './considerations';
